### ISSUE TITLE
Handling unavailable screens

### ISSUE THREAD

**Issue by csuzw** [csuzw/VideoReinforcer#1]
If additional screens are unavailable, windows currently default to primary screen.  An option is required to allow prevention of toggling these windows until the required screen is available.

**Comment by johnjwaters** [comment]
Hey hey!

Just wondered how this is coming on! Cheers.

**Comment by csuzw** [comment]
There is now a new option in General Settings called Default to Primary Screen.  By default this is checked and this provides the same functionality as the application currently has.  If you uncheck this box then videos that don't have an appropriate screen will not display until the screen becomes available.  I've done some very quick testing on this and it seems ok, hopefully it's what you are after.  If not (or I've introduced any new bugs) let me know.
